<img src='https://drive.google.com/uc?id=1nptVTliqyIIOzwF08JXJkWEvlYUC4_g5'  width="1500" height="300">

<div class="markdown-google-sans">
  <h1>Python</h1>
</div>

Python es uno de los lenguajes de programación más populares para realizar aplicaciones basadas en Inteligencia Artificial, tanto en el ámbito académico como en la industria. Por ello, resulta esencial aprender este lenguaje para cualquier persona interesada en Inteligencia Artificial. En esta Notebook, repasaremos los conceptos básicos de Python.

# NumPy

NumPy es la biblioteca más popular de Python y sirve para almacenar vectores y matrices de números para poder realizar cálculos con ellas. Esto no solo permite escribir código a menudo más conciso, sino que también hace que el código sea más rápido, ya que la mayoría de las rutinas de NumPy se implementan en C para mayor velocidad.

In [1]:
# Debemos importar Numpy antes de poder usarla
import numpy as np

In [ ]:
# Para crear un vector y una matriz se debe usar np.array a una lista
vector = np.array([1, 2, 3])
matriz = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector, matriz

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [5]:
# Buscando el elemnto con posición fila= 1, columna=2
matriz[1, 2]

6

In [6]:
matriz[1]

array([4, 5, 6])

In [7]:
matriz[:, 2]

array([3, 6])

In [8]:
# Dimension del "array"
print(vector.ndim)
print(matriz.ndim)

1
2


In [9]:
# Tamaño del "array"
print(vector.shape)
print(matriz.shape)

(3,)
(2, 3)


In [10]:
# El tipo de datos del "array"
vector.dtype, matriz.dtype

(dtype('int64'), dtype('int64'))

<div class="markdown-google-sans">
  <h1>Ejercicio 1</h1>
</div>

In [ ]:
# Crear un array con dim=2, shape=(4,4) y dtype='np.float64
# Escriba su código acá

array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]],
                dtype=np.float64)
print(array)
print(array.dtype)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
float64


In [19]:
# Creando "array" con todos los elementos en 0
ceros = np.zeros((2, 3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# Creando "array" con todos los elementos en 1
unos = np.ones((2, 3))
unos

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# Creando "array" con todos los elementos en forma ascedente
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
# Creando "array" con todos los elementos en un rango
np.arange(3, 7)

array([3, 4, 5, 6])

<div class="markdown-google-sans">
  <h1>Ejercicio 2</h1>
</div>

In [17]:
# Crear un array de 4x3 y usar .reshape para generar: un array de 3x4 y otro array de 6x2
array_4x3 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9],
                      [10, 11, 12]])


print("==========================ARRAY SIN MODIIFICAR=========================")
print(array_4x3)
print("==========================ARRAY CON RESHAPE DE 3 FILAS 4 COLUMNAS=========================")
print(array_4x3.reshape(3, 4))
print("==========================ARRAY CON RESHAPE DE 6 FILAS 2 COLUMNAS=========================")
print(array_4x3.reshape(6, 2))

==========================ARRAY SIN MODIIFICAR=========================
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
==========================ARRAY CON RESHAPE DE 3 FILAS 4 COLUMNAS=========================
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
==========================ARRAY CON RESHAPE DE 6 FILAS 2 COLUMNAS=========================
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


<div class="markdown-google-sans">
  <h1>Ejercicio 3</h1>
</div>

In [42]:
# Crear un array con elementos ascedentes desde el 10 hasta el 100, y presentar los 30 valores intermedios
#se crea mediante linspace 

def metodo_corto():
    print("METODO CORTO PARA RESOLVER EL EJERCICIO")
    array_completo = np.arange(10, 101)
    array_intermedios = np.linspace(10, 100, 30).astype(int)
    print("array completo")
    print(array_completo)
    print("array con valores intermedios")
    print(array_intermedios)

def metodo_largo():
    print("METODO LARGO PARA RESOLVER EL EJERCICIO")
    array_ascendente = np.arange(10, 101)
    print("array completo")
    print(array_ascendente)

    paso = len(array_ascendente) // 30 #divido enteramente la longitud del array entre 30 (100//30 = 3)
    print(f"el paso consecutivo es {paso}")

    valores_intermedios = [] #creo una lista vacia para almacenar los valores intermedios

    for i in range(0, len(array_ascendente), paso):
        valores_intermedios.append(array_ascendente[i]) #agrego los valores intermedios a la lista

    print("array con valores intermedios")
    print(valores_intermedios)

metodo_corto()
metodo_largo()

METODO CORTO PARA RESOLVER EL EJERCICIO
array completo
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
array con valores intermedios
[ 10  13  16  19  22  25  28  31  34  37  41  44  47  50  53  56  59  62
  65  68  72  75  78  81  84  87  90  93  96 100]
METODO LARGO PARA RESOLVER EL EJERCICIO
array completo
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 

<div class="markdown-google-sans">
  <h1>Ejercicio 4</h1>
</div>

In [54]:
# Crear un 3d array (dim=3) con tamaño (2,2,2) que contenga 8 valores. Acceder a cada uno de los elementos individuales y por filas y columnas

array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
    ])

print(array_3d)
print("\nElemento en [0, 0, 0]:", array_3d[0, 0, 0])  # 1
print("Elemento en [0, 0, 1]:", array_3d[0, 0, 1])  # 2
print("Elemento en [0, 1, 0]:", array_3d[0, 1, 0])  # 3
print("Elemento en [0, 1, 1]:", array_3d[0, 1, 1])  # 4
print("Elemento en [1, 0, 0]:", array_3d[1, 0, 0])  # 5
print("Elemento en [1, 0, 1]:", array_3d[1, 0, 1])  # 6
print("Elemento en [1, 1, 0]:", array_3d[1, 1, 0])  # 7
print("Elemento en [1, 1, 1]:", array_3d[1, 1, 1])  # 7


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Elemento en [0, 0, 0]: 1
Elemento en [0, 0, 1]: 2
Elemento en [0, 1, 0]: 3
Elemento en [0, 1, 1]: 4
Elemento en [1, 0, 0]: 5
Elemento en [1, 0, 1]: 6
Elemento en [1, 1, 0]: 7
Elemento en [1, 1, 1]: 8


<div class="markdown-google-sans">
  <h1>Ejercicio 5</h1>
</div>

In [3]:
# Defina el siguiente arreglo y calcule la media. Media es la suma de los elementos dividido por el número de elementos
arreglo = np.arange(3, 6)
suma = sum(arreglo/len(arreglo))
media = np.mean(arreglo)
print(arreglo)
print(media)
print(suma)

[3 4 5]
4.0
4.0


<div class="markdown-google-sans">
  <h1>Ejercicio 6</h1>
</div>

In [ ]:
# Defina el siguiente arreglo y genere un nuevo array que contenga cada uno de sus elementos elevado al cubo
array = np.array([[1, 2, 3],[4, 5, 6]])
print(array)
print("==========================ARRAY CUBO=============================")
array_cubo = array ** 3 
print(array_cubo)

[[1 2 3]
 [4 5 6]]
==========================ARRAY CUBO=========================
[[  1   8  27]
 [ 64 125 216]]


<div class="markdown-google-sans">
  <h1>Ejercicio 7</h1>
</div>

In [ ]:
# Calcule la norma euclidiana del siguiente vector (ver siguiente https://es.wikipedia.org/wiki/Norma_vectorial)
norma_euc = np.array([0.5, -1.2, 3.3, 4.5])

#la norma euclidiana se calcula como la raiz cuadrada de la suma de los cuadrados de cada uno de los elementos
suma = sum(norma_euc ** 2)
norma = np.sqrt(suma)
print(norma)

5.729746940310715


<div class="markdown-google-sans">
  <h1>Ejercicio 8</h1>
</div>

In [33]:
# Calcule la norma euclidiana del siguiente 2d array (ver siguiente https://es.wikipedia.org/wiki/Norma_vectorial)
array2d = np.array([[0.5, -1.2, 4.5],
          [-3.2, 1.9, 2.7]])

print("CONVIERTO EL ARRAY 2D A UN ARRAY SIMPLE")

array1d = array2d.flatten()
print("ARRAY CONVERTIDO A 1D")
print(array1d)
suma  = sum(array1d ** 2)
normal = np.sqrt(suma)
print(f"norma euclidiana: {normal}")

CONVIERTO EL ARRAY 2D A UN ARRAY SIMPLE
ARRAY CONVERTIDO A 1D
[ 0.5 -1.2  4.5 -3.2  1.9  2.7]
norma euclidiana: 6.563535632568776


* [NumPy](https://numpy.org/doc/stable/reference/)
* [SciPy](https://scipy-lectures.org/)
* Youtube [tutorial](https://www.youtube.com/watch?v=QUT1VHiLmmI)



<img src='https://drive.google.com/uc?id=1JTvS_vjZTzQfHiMOt9ZbfqmjNN1FvOOm'>